apiVersion: 1

deleteDatasources:
  - name: InfluxDB-Jenkins

datasources:
  - name: InfluxDB_Jenkins
    type: influxdb
    access: proxy
    url: http://influxdb-jenkins:8086
    isDefault: true
    editable: false
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
    secureJsonData:
      token: ${GF_INFLUXDB_TOKEN}
